language: node_js
node_js: stable
dist: trusty
addons:
#  sauce_connect: true
  sonarqube:
      token:
        secure: ${SONAR_TOKEN}
      branches:
        - master

before_install:
  - sudo apt-get update
#  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g npm-run-all
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - npm install
  - npm update

script:
  - npm-run-all clean test build
#  - gulp saucelabs

after_success:
#  - sonar-scanner
cache:
  directories:
    - '$HOME/.sonar/cache'