language: node_js
node_js: stable
dist: trusty
addons:
#  sauce_connect: true
  sonarqube:
      token:
        secure: ${SONAR_TOKEN}
      branches:
        - master

before_script:
  - npm install -g npm-run-all
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - npm install
  - npm update

script:
  - npm-run-all clean test build
#  - gulp saucelabs

after_success:
#  - sonar-scanner
cache:
  directories:
    - '$HOME/.sonar/cache'