language: node_js
node_js: stable
dist: trusty
addons:
  sauce_connect: true
  sonarqube:
      token:
        secure: ${SONAR_TOKEN}
      branches:
        - master

before_script:
  - npm install
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - npm install
  - npm update
  - bower update

script:
  - gulp clean verify build
  - gulp saucelabs

after_success:
  - sonar-scanner
cache:
  directories:
    - '$HOME/.sonar/cache'